name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout fastapi-app repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: leeh1012/fastapi-app-app:latest,leeh1012/fastapi-app-app:${{ github.sha }}

    - name: Checkout k8s-manifests repo
      uses: actions/checkout@v3
      with:
        repository: leilianecavalcante/k8s-manifests
        token: ${{ secrets.K8S_MANIFESTS_PAT }}
        path: k8s-manifests

    - name: Atualizar deployment.yaml com nova tag da imagem
      run: |
        sed -i "s|image: leeh1012/fastapi-app-app:.*|image: leeh1012/fastapi-app-app:${{ github.sha }}|" k8s-manifests/deployment.yaml

    - name: Criar Pull Request para atualizar manifest
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.K8S_MANIFESTS_PAT }}
        commit-message: Atualiza imagem fastapi-app para ${{ github.sha }}
        branch: update-image-${{ github.sha }}
        title: Atualiza imagem fastapi-app para ${{ github.sha }}
        body: Atualização automática da imagem via GitHub Actions
        base: main
        path: k8s-manifests
